services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Kodigo-002!
      - MSSQL_PID=Developer
    user: root
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Kodigo-002! -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_configurator
    user: root
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - .:/docker-entrypoint-initdb.d
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Kodigo-002! -C -d master -i /docker-entrypoint-initdb.d/init.sql;
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Kodigo-002! -C -d CourseDB -i /docker-entrypoint-initdb.d/data.sql;
      echo "All done!";
      '

volumes:
  sqlserver_data: